---
apiVersion: v1
kind: Namespace
metadata:
  name: dc
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
  namespace: dc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: 'aksmaster.azurecr.io/base/redis:v1'
      imagePullSecrets:
        - name: acr-secret-secondary
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
  namespace: dc
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: http
  selector:
    app: redis
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rng
  labels:
    app: rng
  namespace: dc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rng
    spec:
      containers:
        - name: rng
          image: 'aksmaster.azurecr.io/dockecoins/rng:v1'
      imagePullSecrets:
        - name: acr-secret-secondary
---
apiVersion: v1
kind: Service
metadata:
  name: rng
  labels:
    app: rng
  namespace: dc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: rng
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hasher
  labels:
    app: hasher
  namespace: dc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hasher
    spec:
      containers:
        - name: hasher
          image: 'aksmaster.azurecr.io/dockercoins/hasher:v1'
      imagePullSecrets:
        - name: acr-secret-secondary
---
apiVersion: v1
kind: Service
metadata:
  name: hasher
  labels:
    app: hasher
  namespace: dc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: hasher
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
  namespace: dc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: 'aksmaster.azurecr.io/dockercoins/worker:v1'
      imagePullSecrets:
      - name: acr-secret-secondary
---
apiVersion: v1
kind: Service
metadata:
  name: webui
  labels:
    app: webui
  namespace: dc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: webui
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webui
  labels:
    app: webui
  namespace: dc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - name: webui
          image: aksmaster.azurecr.io/dockercoins/webui:v2
      imagePullSecrets:
        - name: acr-secret-secondary
